// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9LYhUabtO35VB7UhfWnG6xeQ-5FOxgwM',
    appId: '1:1023392936660:web:20e2f3921012dc9afd4141',
    messagingSenderId: '1023392936660',
    projectId: 'raglanma-party',
    authDomain: 'raglanma-party.firebaseapp.com',
    storageBucket: 'raglanma-party.appspot.com',
    measurementId: 'G-YX2RCVB30B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4fHaRGZ_zaBhWhPdN1Hte1j9dAKJsRMM',
    appId: '1:1023392936660:android:37a44648b9a31e89fd4141',
    messagingSenderId: '1023392936660',
    projectId: 'raglanma-party',
    storageBucket: 'raglanma-party.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHq9gfxMPq6dP8Wob3dLJtWAAG80zri0',
    appId: '1:1023392936660:ios:8e69473e33fa1a1ffd4141',
    messagingSenderId: '1023392936660',
    projectId: 'raglanma-party',
    storageBucket: 'raglanma-party.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzHq9gfxMPq6dP8Wob3dLJtWAAG80zri0',
    appId: '1:1023392936660:ios:2dd3273ea607f0dcfd4141',
    messagingSenderId: '1023392936660',
    projectId: 'raglanma-party',
    storageBucket: 'raglanma-party.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
